version: '3.8'

services:
  ### DATABASES
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: labhaze
      MONGO_INITDB_ROOT_PASSWORD: labhaze
      MONGO_INITDB_DATABASE: crypto_viz
    networks:
      - default

  ### REDPANDA
  redpanda:
    container_name: redpanda
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    volumes:
      - redpanda:/var/lib/redpanda/data
    networks:
      - default

  redpanda-ui:
    depends_on:
      - redpanda
    image: redpandadata/console
    container_name: redpanda-ui
    ports:
      - 8085:8080
    environment:
      - KAFKA_BROKERS=redpanda:9092
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    networks:
      - default

  ### BACK
  producer:
    build: ./producer
    depends_on:
      - redpanda
      - mongodb
    container_name: node-producer
    ports:
      - "5010:5000"
    environment:
      - REDPANDA_BROKERS=redpanda:9092
    restart: always
    networks:
      - default

  consumer:
    build: ./consumer
    depends_on:
      - redpanda
      - mongodb
    container_name: node-consumer
    ports:
      - "5001:5000"  # Port modifié pour éviter les conflits
    environment:
      - REDPANDA_BROKERS=redpanda:9092
      - MONGODB_URI=mongodb+srv://labhaze:labhaze@crypto.wgao2i4.mongodb.net/?retryWrites=true&w=majority
    restart: always
    networks:
      - default

  wharehouse:
    build: ./whareHouse
    container_name: node-wharehouse
    restart: always
    ports:
      - "5432:5432"
    networks:
      - default

  api:
    build: ./api
    container_name: node-api
    ports:
      - "8000:8000"
    restart: always
    networks:
      - default

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    networks:
      - default

### VOLUMES
volumes:
  mongodb:
  redpanda:
  clickhouse:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24